name: kebele_appointment_backend
description: Dart Frog REST API for the Kebele Appointment Management System.
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  dart_frog: ^0.3.6
  mysql1: ^0.20.0
  dart_jsonwebtoken: ^2.7.1

dev_dependencies:
  very_good_analysis: ^4.0.0
